spring:
    datasource:
      url: jdbc:mysql://localhost:3306/shiro?charcterEncoding=utf-8&useSSL=false
      username: root
      password: wsgsx2914
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update